
package servicios;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PublicadorConsultarUsuarioService", targetNamespace = "http://Servicios/", wsdlLocation = "http://127.0.0.1:8280/servicioConsultaU?wsdl")
public class PublicadorConsultarUsuarioService
    extends Service
{

    private final static URL PUBLICADORCONSULTARUSUARIOSERVICE_WSDL_LOCATION;
    private final static WebServiceException PUBLICADORCONSULTARUSUARIOSERVICE_EXCEPTION;
    private final static QName PUBLICADORCONSULTARUSUARIOSERVICE_QNAME = new QName("http://Servicios/", "PublicadorConsultarUsuarioService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8280/servicioConsultaU?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PUBLICADORCONSULTARUSUARIOSERVICE_WSDL_LOCATION = url;
        PUBLICADORCONSULTARUSUARIOSERVICE_EXCEPTION = e;
    }

    public PublicadorConsultarUsuarioService() {
        super(__getWsdlLocation(), PUBLICADORCONSULTARUSUARIOSERVICE_QNAME);
    }

    public PublicadorConsultarUsuarioService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PUBLICADORCONSULTARUSUARIOSERVICE_QNAME, features);
    }

    public PublicadorConsultarUsuarioService(URL wsdlLocation) {
        super(wsdlLocation, PUBLICADORCONSULTARUSUARIOSERVICE_QNAME);
    }

    public PublicadorConsultarUsuarioService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PUBLICADORCONSULTARUSUARIOSERVICE_QNAME, features);
    }

    public PublicadorConsultarUsuarioService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PublicadorConsultarUsuarioService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PublicadorConsultarUsuario
     */
    @WebEndpoint(name = "PublicadorConsultarUsuarioPort")
    public PublicadorConsultarUsuario getPublicadorConsultarUsuarioPort() {
        return super.getPort(new QName("http://Servicios/", "PublicadorConsultarUsuarioPort"), PublicadorConsultarUsuario.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PublicadorConsultarUsuario
     */
    @WebEndpoint(name = "PublicadorConsultarUsuarioPort")
    public PublicadorConsultarUsuario getPublicadorConsultarUsuarioPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Servicios/", "PublicadorConsultarUsuarioPort"), PublicadorConsultarUsuario.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PUBLICADORCONSULTARUSUARIOSERVICE_EXCEPTION!= null) {
            throw PUBLICADORCONSULTARUSUARIOSERVICE_EXCEPTION;
        }
        return PUBLICADORCONSULTARUSUARIOSERVICE_WSDL_LOCATION;
    }

}
