
package servicios;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PublicadorAltaUsuario", targetNamespace = "http://Servicios/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface PublicadorAltaUsuario {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://Servicios/PublicadorAltaUsuario/publicarAltaUsuarioRequest", output = "http://Servicios/PublicadorAltaUsuario/publicarAltaUsuarioResponse")
    public void publicarAltaUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param nick
     * @param fecha
     * @param apellido
     * @param correo
     * @param nombreimg
     * @param extencion
     * @param arreglo
     * @param nombre
     * @param hash
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "AgregarUsuarioColaborador")
    @WebResult(partName = "return")
    @Action(input = "http://Servicios/PublicadorAltaUsuario/AgregarUsuarioColaboradorRequest", output = "http://Servicios/PublicadorAltaUsuario/AgregarUsuarioColaboradorResponse")
    public boolean agregarUsuarioColaborador(
        @WebParam(name = "nick", partName = "nick")
        String nick,
        @WebParam(name = "nombre", partName = "nombre")
        String nombre,
        @WebParam(name = "apellido", partName = "apellido")
        String apellido,
        @WebParam(name = "correo", partName = "correo")
        String correo,
        @WebParam(name = "fecha", partName = "fecha")
        String fecha,
        @WebParam(name = "hash", partName = "hash")
        String hash,
        @WebParam(name = "arreglo", partName = "arreglo")
        byte[] arreglo,
        @WebParam(name = "nombreimg", partName = "nombreimg")
        String nombreimg,
        @WebParam(name = "extencion", partName = "extencion")
        String extencion);

    /**
     * 
     * @param nick
     * @param fecha
     * @param sitio
     * @param apellido
     * @param correo
     * @param direccion
     * @param biografia
     * @param nombreimg
     * @param extencion
     * @param arreglo
     * @param nombre
     * @param hash
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "AgregarUsuarioProponente")
    @WebResult(partName = "return")
    @Action(input = "http://Servicios/PublicadorAltaUsuario/AgregarUsuarioProponenteRequest", output = "http://Servicios/PublicadorAltaUsuario/AgregarUsuarioProponenteResponse")
    public boolean agregarUsuarioProponente(
        @WebParam(name = "nick", partName = "nick")
        String nick,
        @WebParam(name = "nombre", partName = "nombre")
        String nombre,
        @WebParam(name = "apellido", partName = "apellido")
        String apellido,
        @WebParam(name = "correo", partName = "correo")
        String correo,
        @WebParam(name = "fecha", partName = "fecha")
        String fecha,
        @WebParam(name = "direccion", partName = "direccion")
        String direccion,
        @WebParam(name = "biografia", partName = "biografia")
        String biografia,
        @WebParam(name = "sitio", partName = "sitio")
        String sitio,
        @WebParam(name = "hash", partName = "hash")
        String hash,
        @WebParam(name = "arreglo", partName = "arreglo")
        byte[] arreglo,
        @WebParam(name = "nombreimg", partName = "nombreimg")
        String nombreimg,
        @WebParam(name = "extencion", partName = "extencion")
        String extencion);

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod(operationName = "ParseFecha")
    @WebResult(partName = "return")
    @Action(input = "http://Servicios/PublicadorAltaUsuario/ParseFechaRequest", output = "http://Servicios/PublicadorAltaUsuario/ParseFechaResponse")
    public XMLGregorianCalendar parseFecha(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param nick
     * @param fecha
     * @param sitio
     * @param apellido
     * @param correo
     * @param direccion
     * @param biografia
     * @param nombre
     * @param hash
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "AgregarUsuarioProponente2")
    @WebResult(partName = "return")
    @Action(input = "http://Servicios/PublicadorAltaUsuario/AgregarUsuarioProponente2Request", output = "http://Servicios/PublicadorAltaUsuario/AgregarUsuarioProponente2Response")
    public boolean agregarUsuarioProponente2(
        @WebParam(name = "nick", partName = "nick")
        String nick,
        @WebParam(name = "nombre", partName = "nombre")
        String nombre,
        @WebParam(name = "apellido", partName = "apellido")
        String apellido,
        @WebParam(name = "correo", partName = "correo")
        String correo,
        @WebParam(name = "fecha", partName = "fecha")
        String fecha,
        @WebParam(name = "direccion", partName = "direccion")
        String direccion,
        @WebParam(name = "biografia", partName = "biografia")
        String biografia,
        @WebParam(name = "sitio", partName = "sitio")
        String sitio,
        @WebParam(name = "hash", partName = "hash")
        String hash);

    /**
     * 
     * @param nick
     * @param fecha
     * @param apellido
     * @param correo
     * @param nombre
     * @param hash
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "AgregarUsuarioColaborador2")
    @WebResult(partName = "return")
    @Action(input = "http://Servicios/PublicadorAltaUsuario/AgregarUsuarioColaborador2Request", output = "http://Servicios/PublicadorAltaUsuario/AgregarUsuarioColaborador2Response")
    public boolean agregarUsuarioColaborador2(
        @WebParam(name = "nick", partName = "nick")
        String nick,
        @WebParam(name = "nombre", partName = "nombre")
        String nombre,
        @WebParam(name = "apellido", partName = "apellido")
        String apellido,
        @WebParam(name = "correo", partName = "correo")
        String correo,
        @WebParam(name = "fecha", partName = "fecha")
        String fecha,
        @WebParam(name = "hash", partName = "hash")
        String hash);

}
