
package servicios;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PublicadorInicio", targetNamespace = "http://Servicios/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PublicadorInicio {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://Servicios/PublicadorInicio/publicarInicioRequest", output = "http://Servicios/PublicadorInicio/publicarInicioResponse")
    public void publicarInicio(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns servicios.DtListPropuestaWeb
     */
    @WebMethod(operationName = "ListarPropuestasWeb")
    @WebResult(partName = "return")
    @Action(input = "http://Servicios/PublicadorInicio/ListarPropuestasWebRequest", output = "http://Servicios/PublicadorInicio/ListarPropuestasWebResponse")
    public DtListPropuestaWeb listarPropuestasWeb();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servicios/PublicadorInicio/leerPropiedadesRequest", output = "http://Servicios/PublicadorInicio/leerPropiedadesResponse")
    public String leerPropiedades(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param navegador
     * @param sitio
     * @param ip
     * @param so
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servicios/PublicadorInicio/agregarRegistroRequest", output = "http://Servicios/PublicadorInicio/agregarRegistroResponse")
    public boolean agregarRegistro(
        @WebParam(name = "ip", partName = "ip")
        String ip,
        @WebParam(name = "navegador", partName = "navegador")
        String navegador,
        @WebParam(name = "sitio", partName = "sitio")
        String sitio,
        @WebParam(name = "SO", partName = "SO")
        String so);

    /**
     * 
     * @return
     *     returns servicios.DtListConsultaPropuesta
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servicios/PublicadorInicio/getDtPropuestasRequest", output = "http://Servicios/PublicadorInicio/getDtPropuestasResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Servicios/PublicadorInicio/getDtPropuestas/Fault/Exception")
    })
    public DtListConsultaPropuesta getDtPropuestas()
        throws Exception_Exception
    ;

}
