
package servicios;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PublicadorRegistrarColaboracionService", targetNamespace = "http://Servicios/", wsdlLocation = "http://127.0.0.1:8280/servicioRegistrarC?wsdl")
public class PublicadorRegistrarColaboracionService
    extends Service
{

    private final static URL PUBLICADORREGISTRARCOLABORACIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException PUBLICADORREGISTRARCOLABORACIONSERVICE_EXCEPTION;
    private final static QName PUBLICADORREGISTRARCOLABORACIONSERVICE_QNAME = new QName("http://Servicios/", "PublicadorRegistrarColaboracionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8280/servicioRegistrarC?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PUBLICADORREGISTRARCOLABORACIONSERVICE_WSDL_LOCATION = url;
        PUBLICADORREGISTRARCOLABORACIONSERVICE_EXCEPTION = e;
    }

    public PublicadorRegistrarColaboracionService() {
        super(__getWsdlLocation(), PUBLICADORREGISTRARCOLABORACIONSERVICE_QNAME);
    }

    public PublicadorRegistrarColaboracionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PUBLICADORREGISTRARCOLABORACIONSERVICE_QNAME, features);
    }

    public PublicadorRegistrarColaboracionService(URL wsdlLocation) {
        super(wsdlLocation, PUBLICADORREGISTRARCOLABORACIONSERVICE_QNAME);
    }

    public PublicadorRegistrarColaboracionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PUBLICADORREGISTRARCOLABORACIONSERVICE_QNAME, features);
    }

    public PublicadorRegistrarColaboracionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PublicadorRegistrarColaboracionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PublicadorRegistrarColaboracion
     */
    @WebEndpoint(name = "PublicadorRegistrarColaboracionPort")
    public PublicadorRegistrarColaboracion getPublicadorRegistrarColaboracionPort() {
        return super.getPort(new QName("http://Servicios/", "PublicadorRegistrarColaboracionPort"), PublicadorRegistrarColaboracion.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PublicadorRegistrarColaboracion
     */
    @WebEndpoint(name = "PublicadorRegistrarColaboracionPort")
    public PublicadorRegistrarColaboracion getPublicadorRegistrarColaboracionPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Servicios/", "PublicadorRegistrarColaboracionPort"), PublicadorRegistrarColaboracion.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PUBLICADORREGISTRARCOLABORACIONSERVICE_EXCEPTION!= null) {
            throw PUBLICADORREGISTRARCOLABORACIONSERVICE_EXCEPTION;
        }
        return PUBLICADORREGISTRARCOLABORACIONSERVICE_WSDL_LOCATION;
    }

}
