
package servicios;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PublicadorConsultarPropuestaService", targetNamespace = "http://Servicios/", wsdlLocation = "http://127.0.0.1:8280/servicioConsultaP?wsdl")
public class PublicadorConsultarPropuestaService
    extends Service
{

    private final static URL PUBLICADORCONSULTARPROPUESTASERVICE_WSDL_LOCATION;
    private final static WebServiceException PUBLICADORCONSULTARPROPUESTASERVICE_EXCEPTION;
    private final static QName PUBLICADORCONSULTARPROPUESTASERVICE_QNAME = new QName("http://Servicios/", "PublicadorConsultarPropuestaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8280/servicioConsultaP?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PUBLICADORCONSULTARPROPUESTASERVICE_WSDL_LOCATION = url;
        PUBLICADORCONSULTARPROPUESTASERVICE_EXCEPTION = e;
    }

    public PublicadorConsultarPropuestaService() {
        super(__getWsdlLocation(), PUBLICADORCONSULTARPROPUESTASERVICE_QNAME);
    }

    public PublicadorConsultarPropuestaService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PUBLICADORCONSULTARPROPUESTASERVICE_QNAME, features);
    }

    public PublicadorConsultarPropuestaService(URL wsdlLocation) {
        super(wsdlLocation, PUBLICADORCONSULTARPROPUESTASERVICE_QNAME);
    }

    public PublicadorConsultarPropuestaService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PUBLICADORCONSULTARPROPUESTASERVICE_QNAME, features);
    }

    public PublicadorConsultarPropuestaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PublicadorConsultarPropuestaService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PublicadorConsultarPropuesta
     */
    @WebEndpoint(name = "PublicadorConsultarPropuestaPort")
    public PublicadorConsultarPropuesta getPublicadorConsultarPropuestaPort() {
        return super.getPort(new QName("http://Servicios/", "PublicadorConsultarPropuestaPort"), PublicadorConsultarPropuesta.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PublicadorConsultarPropuesta
     */
    @WebEndpoint(name = "PublicadorConsultarPropuestaPort")
    public PublicadorConsultarPropuesta getPublicadorConsultarPropuestaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Servicios/", "PublicadorConsultarPropuestaPort"), PublicadorConsultarPropuesta.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PUBLICADORCONSULTARPROPUESTASERVICE_EXCEPTION!= null) {
            throw PUBLICADORCONSULTARPROPUESTASERVICE_EXCEPTION;
        }
        return PUBLICADORCONSULTARPROPUESTASERVICE_WSDL_LOCATION;
    }

}
