
package servicios;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PublicadorRegistrarColaboracion", targetNamespace = "http://Servicios/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PublicadorRegistrarColaboracion {


    /**
     * 
     * @param opcion
     * @return
     *     returns servicios.DtinfoPropuesta
     */
    @WebMethod(operationName = "SeleccionarPropuestaR")
    @WebResult(partName = "return")
    @Action(input = "http://Servicios/PublicadorRegistrarColaboracion/SeleccionarPropuestaRRequest", output = "http://Servicios/PublicadorRegistrarColaboracion/SeleccionarPropuestaRResponse")
    public DtinfoPropuesta seleccionarPropuestaR(
        @WebParam(name = "opcion", partName = "opcion")
        String opcion);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://Servicios/PublicadorRegistrarColaboracion/publicarRegistrarColaboracionRequest", output = "http://Servicios/PublicadorRegistrarColaboracion/publicarRegistrarColaboracionResponse")
    public void publicarRegistrarColaboracion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns servicios.DtListPropuestasRWEB
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servicios/PublicadorRegistrarColaboracion/listarPropuestasRWEBRequest", output = "http://Servicios/PublicadorRegistrarColaboracion/listarPropuestasRWEBResponse")
    public DtListPropuestasRWEB listarPropuestasRWEB();

    /**
     * 
     * @param nickName
     * @return
     *     returns servicios.DtinfoColaborador
     */
    @WebMethod(operationName = "SeleccionarColaborador")
    @WebResult(partName = "return")
    @Action(input = "http://Servicios/PublicadorRegistrarColaboracion/SeleccionarColaboradorRequest", output = "http://Servicios/PublicadorRegistrarColaboracion/SeleccionarColaboradorResponse")
    public DtinfoColaborador seleccionarColaborador(
        @WebParam(name = "nickName", partName = "nickName")
        String nickName);

    /**
     * 
     * @param retorno
     * @param montoFinal
     * @return
     *     returns boolean
     * @throws Exception_Exception
     */
    @WebMethod(operationName = "AgregarColaboracion")
    @WebResult(partName = "return")
    @Action(input = "http://Servicios/PublicadorRegistrarColaboracion/AgregarColaboracionRequest", output = "http://Servicios/PublicadorRegistrarColaboracion/AgregarColaboracionResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Servicios/PublicadorRegistrarColaboracion/AgregarColaboracion/Fault/Exception")
    })
    public boolean agregarColaboracion(
        @WebParam(name = "retorno", partName = "retorno")
        boolean retorno,
        @WebParam(name = "monto_final", partName = "monto_final")
        float montoFinal)
        throws Exception_Exception
    ;

}
