
package servicios;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PublicadorAltaPropuesta", targetNamespace = "http://Servicios/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PublicadorAltaPropuesta {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://Servicios/PublicadorAltaPropuesta/publicarRequest", output = "http://Servicios/PublicadorAltaPropuesta/publicarResponse")
    public void publicar(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns servicios.DtCategorias
     */
    @WebMethod(operationName = "ListarCategorias")
    @WebResult(partName = "return")
    @Action(input = "http://Servicios/PublicadorAltaPropuesta/ListarCategoriasRequest", output = "http://Servicios/PublicadorAltaPropuesta/ListarCategoriasResponse")
    public DtCategorias listarCategorias();

    /**
     * 
     * @param descripcion
     * @param fecha
     * @param retorno
     * @param lugar
     * @param montoTot
     * @param tituloP
     * @param montoE
     * @return
     *     returns boolean
     * @throws Exception_Exception
     */
    @WebMethod(operationName = "CrearPropuesta")
    @WebResult(partName = "return")
    @Action(input = "http://Servicios/PublicadorAltaPropuesta/CrearPropuestaRequest", output = "http://Servicios/PublicadorAltaPropuesta/CrearPropuestaResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Servicios/PublicadorAltaPropuesta/CrearPropuesta/Fault/Exception")
    })
    public boolean crearPropuesta(
        @WebParam(name = "tituloP", partName = "tituloP")
        String tituloP,
        @WebParam(name = "descripcion", partName = "descripcion")
        String descripcion,
        @WebParam(name = "lugar", partName = "lugar")
        String lugar,
        @WebParam(name = "fecha", partName = "fecha")
        String fecha,
        @WebParam(name = "montoE", partName = "montoE")
        float montoE,
        @WebParam(name = "montoTot", partName = "montoTot")
        float montoTot,
        @WebParam(name = "retorno", partName = "retorno")
        String retorno)
        throws Exception_Exception
    ;

    /**
     * 
     * @param nick
     * @param categoria
     * @return
     *     returns boolean
     * @throws Exception_Exception
     */
    @WebMethod(operationName = "SeleccionarUC")
    @WebResult(partName = "return")
    @Action(input = "http://Servicios/PublicadorAltaPropuesta/SeleccionarUCRequest", output = "http://Servicios/PublicadorAltaPropuesta/SeleccionarUCResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Servicios/PublicadorAltaPropuesta/SeleccionarUC/Fault/Exception")
    })
    public boolean seleccionarUC(
        @WebParam(name = "nick", partName = "nick")
        String nick,
        @WebParam(name = "categoria", partName = "categoria")
        String categoria)
        throws Exception_Exception
    ;

}
