
package servicios;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PublicadorConsultarPropuesta", targetNamespace = "http://Servicios/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PublicadorConsultarPropuesta {


    /**
     * 
     * @param titulo
     * @param nickProp
     * @return
     *     returns servicios.DtConsultaPropuesta
     */
    @WebMethod(operationName = "SeleccionarPropuesta")
    @WebResult(partName = "return")
    @Action(input = "http://Servicios/PublicadorConsultarPropuesta/SeleccionarPropuestaRequest", output = "http://Servicios/PublicadorConsultarPropuesta/SeleccionarPropuestaResponse")
    public DtConsultaPropuesta seleccionarPropuesta(
        @WebParam(name = "titulo", partName = "titulo")
        String titulo,
        @WebParam(name = "nickProp", partName = "nickProp")
        String nickProp);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://Servicios/PublicadorConsultarPropuesta/publicarConsultaPropuestaRequest", output = "http://Servicios/PublicadorConsultarPropuesta/publicarConsultaPropuestaResponse")
    public void publicarConsultaPropuesta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param titulo
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "ExtenderFinanciacion")
    @WebResult(partName = "return")
    @Action(input = "http://Servicios/PublicadorConsultarPropuesta/ExtenderFinanciacionRequest", output = "http://Servicios/PublicadorConsultarPropuesta/ExtenderFinanciacionResponse")
    public boolean extenderFinanciacion(
        @WebParam(name = "titulo", partName = "titulo")
        String titulo);

    /**
     * 
     * @param nombre
     * @return
     *     returns servicios.DtListInfoPropuesta
     */
    @WebMethod(operationName = "ListarPropuestasCategoria")
    @WebResult(partName = "return")
    @Action(input = "http://Servicios/PublicadorConsultarPropuesta/ListarPropuestasCategoriaRequest", output = "http://Servicios/PublicadorConsultarPropuesta/ListarPropuestasCategoriaResponse")
    public DtListInfoPropuesta listarPropuestasCategoria(
        @WebParam(name = "nombre", partName = "nombre")
        String nombre);

    /**
     * 
     * @param nick
     * @return
     *     returns servicios.DtListNickTitProp
     */
    @WebMethod(operationName = "ListarPropuestasCancelar")
    @WebResult(partName = "return")
    @Action(input = "http://Servicios/PublicadorConsultarPropuesta/ListarPropuestasCancelarRequest", output = "http://Servicios/PublicadorConsultarPropuesta/ListarPropuestasCancelarResponse")
    public DtListNickTitProp listarPropuestasCancelar(
        @WebParam(name = "nick", partName = "nick")
        String nick);

    /**
     * 
     * @param nick
     * @param texto
     * @param titulo
     * @throws Exception_Exception
     */
    @WebMethod(operationName = "ComentarPropuesta")
    @Action(input = "http://Servicios/PublicadorConsultarPropuesta/ComentarPropuestaRequest", output = "http://Servicios/PublicadorConsultarPropuesta/ComentarPropuestaResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Servicios/PublicadorConsultarPropuesta/ComentarPropuesta/Fault/Exception")
    })
    public void comentarPropuesta(
        @WebParam(name = "titulo", partName = "titulo")
        String titulo,
        @WebParam(name = "nick", partName = "nick")
        String nick,
        @WebParam(name = "texto", partName = "texto")
        String texto)
        throws Exception_Exception
    ;

    /**
     * 
     * @param nick
     * @param titulo
     * @return
     *     returns boolean
     * @throws Exception_Exception
     */
    @WebMethod(operationName = "CancelarPropuesta")
    @WebResult(partName = "return")
    @Action(input = "http://Servicios/PublicadorConsultarPropuesta/CancelarPropuestaRequest", output = "http://Servicios/PublicadorConsultarPropuesta/CancelarPropuestaResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Servicios/PublicadorConsultarPropuesta/CancelarPropuesta/Fault/Exception")
    })
    public boolean cancelarPropuesta(
        @WebParam(name = "titulo", partName = "titulo")
        String titulo,
        @WebParam(name = "nick", partName = "nick")
        String nick)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns servicios.DtListConsultaPropuesta
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servicios/PublicadorConsultarPropuesta/getDtPropuestasRequest", output = "http://Servicios/PublicadorConsultarPropuesta/getDtPropuestasResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Servicios/PublicadorConsultarPropuesta/getDtPropuestas/Fault/Exception")
    })
    public DtListConsultaPropuesta getDtPropuestas()
        throws Exception_Exception
    ;

    /**
     * 
     * @param titulo
     * @return
     *     returns byte[]
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servicios/PublicadorConsultarPropuesta/retornarImagenRequest", output = "http://Servicios/PublicadorConsultarPropuesta/retornarImagenResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Servicios/PublicadorConsultarPropuesta/retornarImagen/Fault/Exception")
    })
    public byte[] retornarImagen(
        @WebParam(name = "titulo", partName = "titulo")
        String titulo)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns servicios.DtListNickTitProp
     */
    @WebMethod(operationName = "ListarPropuestas")
    @WebResult(partName = "return")
    @Action(input = "http://Servicios/PublicadorConsultarPropuesta/ListarPropuestasRequest", output = "http://Servicios/PublicadorConsultarPropuesta/ListarPropuestasResponse")
    public DtListNickTitProp listarPropuestas();

    /**
     * 
     * @param titulo
     * @return
     *     returns servicios.DtConsultaPropuesta
     */
    @WebMethod(operationName = "SeleccionarPropuesta2")
    @WebResult(partName = "return")
    @Action(input = "http://Servicios/PublicadorConsultarPropuesta/SeleccionarPropuesta2Request", output = "http://Servicios/PublicadorConsultarPropuesta/SeleccionarPropuesta2Response")
    public DtConsultaPropuesta seleccionarPropuesta2(
        @WebParam(name = "titulo", partName = "titulo")
        String titulo);

    /**
     * 
     * @param nick
     * @return
     *     returns servicios.DtListNickTitProp
     */
    @WebMethod(operationName = "ListarPropuestasX_deProponenteX")
    @WebResult(partName = "return")
    @Action(input = "http://Servicios/PublicadorConsultarPropuesta/ListarPropuestasX_deProponenteXRequest", output = "http://Servicios/PublicadorConsultarPropuesta/ListarPropuestasX_deProponenteXResponse")
    public DtListNickTitProp listarPropuestasXDeProponenteX(
        @WebParam(name = "nick", partName = "nick")
        String nick);

    /**
     * 
     * @return
     *     returns servicios.DtListNickTitProp
     */
    @WebMethod(operationName = "ListarPropuestasComentar")
    @WebResult(partName = "return")
    @Action(input = "http://Servicios/PublicadorConsultarPropuesta/ListarPropuestasComentarRequest", output = "http://Servicios/PublicadorConsultarPropuesta/ListarPropuestasComentarResponse")
    public DtListNickTitProp listarPropuestasComentar();

    /**
     * 
     * @param titulo
     * @return
     *     returns servicios.DtListConsultaPropuesta2
     * @throws Exception_Exception
     */
    @WebMethod(operationName = "ListarColaboradoresProp")
    @WebResult(partName = "return")
    @Action(input = "http://Servicios/PublicadorConsultarPropuesta/ListarColaboradoresPropRequest", output = "http://Servicios/PublicadorConsultarPropuesta/ListarColaboradoresPropResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Servicios/PublicadorConsultarPropuesta/ListarColaboradoresProp/Fault/Exception")
    })
    public DtListConsultaPropuesta2 listarColaboradoresProp(
        @WebParam(name = "titulo", partName = "titulo")
        String titulo)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns servicios.DtListInfoPropuesta
     */
    @WebMethod(operationName = "ListarPropuestasNoI")
    @WebResult(partName = "return")
    @Action(input = "http://Servicios/PublicadorConsultarPropuesta/ListarPropuestasNoIRequest", output = "http://Servicios/PublicadorConsultarPropuesta/ListarPropuestasNoIResponse")
    public DtListInfoPropuesta listarPropuestasNoI();

    /**
     * 
     * @param tituloP
     * @return
     *     returns servicios.DtListComentarios
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servicios/PublicadorConsultarPropuesta/listarComentariosRequest", output = "http://Servicios/PublicadorConsultarPropuesta/listarComentariosResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Servicios/PublicadorConsultarPropuesta/listarComentarios/Fault/Exception")
    })
    public DtListComentarios listarComentarios(
        @WebParam(name = "TituloP", partName = "TituloP")
        String tituloP)
        throws Exception_Exception
    ;

}
