
package servicios;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PublicadorAltaUsuarioService", targetNamespace = "http://Servicios/", wsdlLocation = "http://127.0.0.1:8280/servicioAltaUsuario?wsdl")
public class PublicadorAltaUsuarioService
    extends Service
{

    private final static URL PUBLICADORALTAUSUARIOSERVICE_WSDL_LOCATION;
    private final static WebServiceException PUBLICADORALTAUSUARIOSERVICE_EXCEPTION;
    private final static QName PUBLICADORALTAUSUARIOSERVICE_QNAME = new QName("http://Servicios/", "PublicadorAltaUsuarioService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8280/servicioAltaUsuario?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PUBLICADORALTAUSUARIOSERVICE_WSDL_LOCATION = url;
        PUBLICADORALTAUSUARIOSERVICE_EXCEPTION = e;
    }

    public PublicadorAltaUsuarioService() {
        super(__getWsdlLocation(), PUBLICADORALTAUSUARIOSERVICE_QNAME);
    }

    public PublicadorAltaUsuarioService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PUBLICADORALTAUSUARIOSERVICE_QNAME, features);
    }

    public PublicadorAltaUsuarioService(URL wsdlLocation) {
        super(wsdlLocation, PUBLICADORALTAUSUARIOSERVICE_QNAME);
    }

    public PublicadorAltaUsuarioService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PUBLICADORALTAUSUARIOSERVICE_QNAME, features);
    }

    public PublicadorAltaUsuarioService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PublicadorAltaUsuarioService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PublicadorAltaUsuario
     */
    @WebEndpoint(name = "PublicadorAltaUsuarioPort")
    public PublicadorAltaUsuario getPublicadorAltaUsuarioPort() {
        return super.getPort(new QName("http://Servicios/", "PublicadorAltaUsuarioPort"), PublicadorAltaUsuario.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PublicadorAltaUsuario
     */
    @WebEndpoint(name = "PublicadorAltaUsuarioPort")
    public PublicadorAltaUsuario getPublicadorAltaUsuarioPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Servicios/", "PublicadorAltaUsuarioPort"), PublicadorAltaUsuario.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PUBLICADORALTAUSUARIOSERVICE_EXCEPTION!= null) {
            throw PUBLICADORALTAUSUARIOSERVICE_EXCEPTION;
        }
        return PUBLICADORALTAUSUARIOSERVICE_WSDL_LOCATION;
    }

}
