
package servicios;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PublicadorInicioService", targetNamespace = "http://Servicios/", wsdlLocation = "http://127.0.0.1:8280/servicioInicio?wsdl")
public class PublicadorInicioService
    extends Service
{

    private final static URL PUBLICADORINICIOSERVICE_WSDL_LOCATION;
    private final static WebServiceException PUBLICADORINICIOSERVICE_EXCEPTION;
    private final static QName PUBLICADORINICIOSERVICE_QNAME = new QName("http://Servicios/", "PublicadorInicioService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8280/servicioInicio?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PUBLICADORINICIOSERVICE_WSDL_LOCATION = url;
        PUBLICADORINICIOSERVICE_EXCEPTION = e;
    }

    public PublicadorInicioService() {
        super(__getWsdlLocation(), PUBLICADORINICIOSERVICE_QNAME);
    }

    public PublicadorInicioService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PUBLICADORINICIOSERVICE_QNAME, features);
    }

    public PublicadorInicioService(URL wsdlLocation) {
        super(wsdlLocation, PUBLICADORINICIOSERVICE_QNAME);
    }

    public PublicadorInicioService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PUBLICADORINICIOSERVICE_QNAME, features);
    }

    public PublicadorInicioService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PublicadorInicioService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PublicadorInicio
     */
    @WebEndpoint(name = "PublicadorInicioPort")
    public PublicadorInicio getPublicadorInicioPort() {
        return super.getPort(new QName("http://Servicios/", "PublicadorInicioPort"), PublicadorInicio.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PublicadorInicio
     */
    @WebEndpoint(name = "PublicadorInicioPort")
    public PublicadorInicio getPublicadorInicioPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Servicios/", "PublicadorInicioPort"), PublicadorInicio.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PUBLICADORINICIOSERVICE_EXCEPTION!= null) {
            throw PUBLICADORINICIOSERVICE_EXCEPTION;
        }
        return PUBLICADORINICIOSERVICE_WSDL_LOCATION;
    }

}
